### ISSUE TITLE
Authentication broken & missing items in menu

### ISSUE THREAD

**Issue by captainark** [poweradmin/poweradmin#273]
I keep my poweradmin installation up-to-date with this repo, and I wasn't able to login when I tried using it today.

After rolling back a few commits, I pinpointed the origin of the issue to [this commit](https://github.com/poweradmin/poweradmin/commit/02ea7d8c0a8ba3945e2b1a9937f9a1630bc307dc).

However, even after reverting to this commit, items where missing in the menu. It seems to have been caused by [this commit](https://github.com/poweradmin/poweradmin/commit/8b94b9d1f87d66a9ea0c8e93baf84b013a5d69f3).

Here's what I see since pulling this commit :
![menu](https://cloud.githubusercontent.com/assets/6699651/13724287/422d46a8-e881-11e5-88a5-152ced71d6a3.png)

Here's what I see when reverting to the commit before that one :
![menu](https://cloud.githubusercontent.com/assets/6699651/13724292/563bad74-e881-11e5-859e-e053ef0325f2.png)

**Comment by charlesa101** [comment]
@captainark: i am experiencing the same issue with this new upgrade...i thought it was a problem with my saltstack code. thanks for the heads up

**Comment by edmondas** [comment]
I think this issue is already fixed within #272 pull request. Can you update to the latest code and check?

**Comment by captainark** [comment]
Just pulled the latest version ; I'm still getting an "Authentication failed!" message when trying to login with my usual credentials.

Please let me know if I can provide you with any additional information.

**Comment by edmondas** [comment]
Did you see any errors in your error log file? Can you add $password_encryption = 'md5' to your config.inc.php file and try to login.

**Comment by captainark** [comment]
Adding `$password_encryption = 'md5';` to my config.inc.php file fixed it, thanks.

I can see all items in the menu bar as well.

**Comment by charlesa101** [comment]
Cool! works now thanks @edmondas @captainark

**Comment by ricardo777** [comment]
Hello,

I have installed fresh copy of the github with changes of today, on a excisiting powerdns installation.

I have added the $password_encryption = 'md5'; to the config but I can still see only the menu like:

Index
Change password
User administration
Logout

**Comment by edmondas** [comment]
@ricardo777 You are able to login so that means that it's not related to authentication (password hashing), by some reason your account is identified as non admin user.

Can you var_dump($cache); at the end of verify_permission_local function (users_local.plugin.php file)?
After adding it should look something like that:

```
$cache = $query->fetchAll(PDO::FETCH_GROUP | PDO::FETCH_ASSOC);
var_dump($cache);
return array_key_exists('user_is_ueberuser', $cache) || array_key_exists($permission, $cache);
```
Then try to login to poweradmin admin panel and check if at the top of window you see something like this:
```
array (size=1)
  'user_is_ueberuser' => 
    array (size=1)
      0 => 
        array (size=0)
          empty
```

Also please check if there are no errors in your http server log, because that may also help to resolve this issue.

**Comment by ricardo777** [comment]
There is nothing in the array:

array(0) { }

code is:

```
    $cache = $query->fetchAll(PDO::FETCH_GROUP | PDO::FETCH_ASSOC);
var_dump($cache);
    return array_key_exists('user_is_ueberuser', $cache) || array_key_exists($permission, $cache);
```

There are no errors only 2 old ones:

PHP Notice:  Uninitialized string offset: 32 in /home/nxbalkgz/public_html/Poweradmin/vendor/poweradmin/Password.php on line 149
PHP Fatal error:  Call to undefined function Poweradmin\Password\verify() in /home/nxbalkgz/public_html/Poweradmin/inc/plugins/users_local/users_local.plugin.php on line 398

**Comment by edmondas** [comment]
Very strange, @ricardo777 does this query returns any result?

```
SELECT
	perm_items.name AS permission 
FROM 
	perm_templ_items 
	LEFT JOIN perm_items ON perm_items.id = perm_templ_items.perm_id 
	LEFT JOIN perm_templ ON perm_templ.id = perm_templ_items.templ_id 
	LEFT JOIN users ON perm_templ.id = users.perm_templ
```

Thanks for providing error log entries, I fixed one issue with password changing.

**Comment by ricardo777** [comment]
No:  Weergave van records 0 - 0 (1 totaal, Query duurde 0.0004 seconden.)

> Thanks for providing error log entries, I fixed one issue with password changing.

Yes I tried changing password that was giving me a 500 error

**Comment by edmondas** [comment]
@ricardo777 It seems that something is wrong with records in your table. The main issue is with perm_templ.id, which in your case has value 3, but for example in users table perm_templ = 1, also perm_templ_items.templ_id is 1. Not sure how this happen, but if you will set perm_templ.id to 1, then everything will work fine.

**Comment by ricardo777** [comment]
@edmondas It worked, thank you.

**Comment by brablc** [comment]
I had the same problem and fixed it by inserting:

`INSERT INTO `perm_templ` (`id`, `name`, `descr`) VALUES ('1', 'Admin', '');`

**Comment by IroHaturo** [comment]
Phresh install, could not log in "Authentication failed" Google brought me here and the last comment @brablc pointed me into the right direction: even though I never added or setup a user "Admin", I can log in as "admin" w. MY password? The user I entered during setup does not exist.
[Poweradmin v3.5.0] on Deb12

**Comment by edmondas** [comment]
@IroHaturo By default, the user name created during installation is admin, the username mentioned on installation step 4 is for the database, to have a separate user with minimal rights. It is always possible to change the main user name in the user management panel at a later time.
