### ISSUE TITLE
Save Changes button seems to have no effect in Edit Zone page, changes are not saved

### ISSUE THREAD

**Issue by michielvisser** [poweradmin/poweradmin#690]
Not sure when this has regressed but in the latest commit cb76e82 I've checked out today the Save Changes button in the Zone Edit form does not work. 

There is no feedback that zone has been saved and when reloading the page all edits are gone. No errors in my PHP log either, unfortunately so cannot pinpoint what is happening exactly. All the other buttons seem to work fine - Export CSV, batch PTR and so on.

**Comment by michielvisser** [comment]
I've did some more tests regarding this issue:

1. The issue happens with both zones that have a template assigned and to zones without an associated template.
2. It is not a matter of user rights, happens with all users as far as I can test
3. It does not matter whether the record is created by a template or it is a record that created from the gui in the zone edit form itself by adding a new record
4. I had a suspicion at first that this happened only when the option for show hostnames only was enabled but it also doesn't work with that interface setting disabled. However, this got me noticing a weird quirk that might be related or not - when records are created via a template, they will always get the name exactly as specified in the template and are not expanded to their FQDN:

![Image](https://github.com/user-attachments/assets/bf023b4f-d0c0-47ca-b43a-8cf6e7d7628e)

See the www record here as an example. The mail.mcvesta.net record was specified that way in the template and thus is correct. test.mcvesta.net was created as test manually to see if I could change it - not part of the template.

For completeness, this is the template associated with the zone:

![Image](https://github.com/user-attachments/assets/ad864151-a485-449d-ba64-d24a476e6e08)

This might be the correct behaviour as designed but I would have expected that as happens with manually added records that hostnames from template are automatically expanded to FQDN in the underlying processing.

I only noticed this because I switched off the setting for the hostnames in the config file.

Hope this helps pinpointing the issue.

**Comment by edmondas** [comment]
@michielvisser The issue should be resolved now - I accidentally added unnecessary checks.

**Comment by michielvisser** [comment]
@edmondas I cannot unfortunately reopen the issue but after checking out commit 5257a79 I tested and it still doesn't work:

- Adding new records with the form at the top works fine
- Changing an A record (put in a new IP) and then click Save Changes in the form with the records does not save the changes, the only thing that happens as far as I can see is that the content fields of the records in the zone are highlighted with a black border and then nothing happens:

![Image](https://github.com/user-attachments/assets/4823d987-8f90-4720-b83f-26e262b668e4)

**Comment by edmondas** [comment]
@michielvisser I've granted you reader access to the project, which should allow you to reopen the issue according to the documentation. Please check if you received an invitation. As for the issue itself, I'll take a look when I have some free time. There might still be some problems - I'm considering rewriting the change tracking part since it's difficult to maintain and tends to break whenever new fields are added.

**Comment by michielvisser** [comment]
@edmondas Thanks for granting reader access in the first place. I've been doing some more testing, going through the various commits to see where it actually broke.

Going back, I found that the last working commit was a974238 of April 25th. The next commit after that a974238 for improvement of the form structure actually broke the Save Changes button. Looking through the commit, the file that most likely is the culprit is the edit.hml file in the templates, where some changes were made in the div-structure.

And after some more experiments, I can confirm it is definitely this file as I can replace the edit.html with the contents from the previous commit and then the form works again.

At the moment of writing this comment I am trying to understand how the template exactly works and why it broke. If I can figure it out I will try see if I can fix it and if so, submit a PR.

**Comment by edmondas** [comment]
After reviewing the edit.html file, I removed the extra closing `</div>` tag on line 491 - an orphaned tag that my IDE clearly flagged as having no corresponding opening tag.
