### ISSUE TITLE
[bug] Docker HealthCheck of Caddy Administrative Port

### ISSUE THREAD

**Issue by zzqzzqzzq** [poweradmin/poweradmin#851]
It appears the PowerAdmin docker image has a health check enabled on the Caddy administrative port (2019), yet the default configuration doesn't seem to enable the requisite bit in Caddy.

An inspect on the container image shows: 

    "Healthcheck": {
      "Test": [
        "CMD-SHELL",
        "curl -f http://localhost:2019/metrics || exit 1"
      ]
    },

Yet I find this in the image's /etc/caddy/Caddyfile:  (Which I presume is what disables the admin port, particularly the "admin off")

{
    frankenphp
    admin off
    order php_server before file_server
}

Obviously the image shows up as unhealthy while running.     

Maybe its part of frankenphp? -- I didn't find said health check in the projects Dockerfile....

I hacked up my docker compose to override the healthcheck with a "stock" curl localhost:80 command and all is good, but I thought you might want the bug report.. 

Cheers!

David

**Comment by edmondas** [comment]
@zzqzzqzzq That's a good finding, thanks for reporting. Should be fixed now (in master - so latest docker tag).

**Comment by layanto** [comment]
<img width="861" height="228" alt="Image" src="https://github.com/user-attachments/assets/f74f857c-de50-4802-9b5f-276a26be61af" />
Portainer still shows PowerAdmin v4.0.5 container as unhealthy.

**Comment by edmondas** [comment]
Fixed in both `latest` and `stable` Docker images.

Changed healthcheck from `wget` to `curl` - BusyBox wget can't handle relative redirects. Both images rebuilt and tested successfully.
